name = "soundscape-admin-headless"
compatibility_date = "2023-10-30"
main = "build/worker/shim.mjs"

[build]
command = "cargo install -q worker-build && worker-build --release"

[[routes]]
pattern = "ach.sound.ct2.io"
custom_domain = true

[[d1_databases]]
binding = "INFO_STORE"
database_name = "soundscape"
database_id = "5b7c43cc-faf9-4bb1-872b-ef4de18009ae"

[[r2_buckets]]
binding = "OBJECT_STORE"
bucket_name = "soundscape"
