// Generated by Wrangler on Thu Apr 18 2024 18:03:38 GMT+0900 (日本標準時)
// by running `wrangler types`

interface Env {
	CONTENT_ID_OBFUSCATOR_KEY: string;
	OBJECT_STORE_S3_ACCESS_KEY: string;
	OBJECT_STORE_S3_SECRET_ACCESS_KEY: string;
	OBJECT_STORE_S3_ENDPOINT: string;
	OBJECT_STORE: R2Bucket;
	INFO_STORE: D1Database;
}
