name = "soundscape"
main = "./worker/index.ts"
compatibility_date = "2023-04-20"

[site]
bucket = "./public"

[[d1_databases]]
binding = "INFO_STORE"
database_name = "soundscape"
database_id = "5b7c43cc-faf9-4bb1-872b-ef4de18009ae"
migrations_dir = "./migrations"

[[r2_buckets]]
binding = "OBJECT_STORE"
bucket_name = "soundscape"
